[build]
  command = "npm run build"
  publish = "build"

[context]
  production = "production"

[functions]
  source = "functions"

[redirects]
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200